common: &common
  solr:
    hostname: localhost
    port: 8983

production:
  <<: *common

development:
  <<: *common
  solr:
    port: 8080
    path: /solr-example

test:
  <<: *common
  solr:
    port: 8983

